version: "3.2"

services:
  localstack:
    container_name: "${LOCALSTACK_DOCKER_NAME-localstack_main}"
    image: localstack/localstack
    ports:
      - "4567-4597:4567-4597"
      - "${PORT_WEB_UI-8080}:${PORT_WEB_UI-8080}"
    environment:
      - SERVICES=dynamodb,dynamodbstreams,lambda,cloudwatch,logs
      - LAMBDA_EXECUTOR=docker-reuse
      - DOCKER_HOST=unix:///var/run/docker.sock
    volumes:
      - "./tmp/localstack:/tmp/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "./provision.sh:/docker-entrypoint-initaws.d/provision.sh"
      - "./SearchPopulator.Lambda.PoC.zip:/Development/SearchPopulator.Lambda.PoC/src/SearchPopulator.Lambda.PoC/bin/Release/netcoreapp2.1/SearchPopulator.Lambda.PoC.zip"
